import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-12 md:p-24">
          <header className="pb-3 mb-6 block relative after:absolute after:left-0 after:bottom-0 after:h-1 after:w-8 after:bg-neutral-500 after:bg-opacity-50 after:rounded">
            <nav>
              <ul>
                <li>
                  <Link className="font-bold mb-2 underline" href="/">
                    GitHub Explorer
                    <span className="sr-only"> frontpage</span>
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
