import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col p-6 md:p-12 max-w-[40rem] mx-auto w-full">
          <header className="pb-3 mb-6 block relative after:absolute after:left-0 after:bottom-0 after:h-1 after:w-8 after:bg-slate-700 after:rounded">
            <nav>
              <ul>
                <li>
                  <Link
                    href={"/"}
                    className="font-bold mb-2 text-blue-700 hover:text-blue-500"
                  >
                    GitHub Explorer
                    <span className="sr-only"> frontpage</span>
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
